name: "CCIS1515 Semester"  # CHANGE ME
baseurl: /semester # CHANGE ME
github_org_url: https://github.com/htc-ccis1515-semester # CHANGE ME
github_org_name: "HTC CCIS1515 Semester" # CHANGE ME

# The following properties should not need to change semester to semester.
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule

gems:
  - jekyll-gist
  - jemoji

morea_course: CCIS 1515
morea_domain: http://htc-ccis1515.github.io/
morea_google_analytics_tracking_id: "UA-63189236-2"
googleCalendarId: 'p30s3h8kvfke697l4cb3g3rp8k@group.calendar.google.com'
